### ISSUE TITLE
npm ERR! 404 Not Found: prefix@latest

### ISSUE THREAD

**Issue by ganesh9255** [mzabriskie/react-example#17]
I am getting below error while run the c:/Users/>npx create-react-app my-app
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'prefix@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\GA5033532\\AppData\\Roaming\\npm-cache\\_npx\\11736',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json' ]
2 info using npm@5.6.0
3 info using node@v10.2.0
4 verbose npm-session 4ef72031b947d105
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 http://registry.npmjs.org/prefix 1600ms
8 silly fetchPackageMetaData error for prefix@latest 404 Not Found: prefix@latest
9 verbose stack Error: 404 Not Found: prefix@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:696:18)
9 verbose stack     at tryOnImmediate (timers.js:667:5)
9 verbose stack     at processImmediate (timers.js:649:5)
10 verbose cwd C:\Users\GA5033532\reactAPP
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "prefix@latest" "--global" "--prefix" "C:\\Users\\GA5033532\\AppData\\Roaming\\npm-cache\\_npx\\11736" "--loglevel" "error" "--json"
13 verbose node v10.2.0
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: prefix@latest
17 verbose exit [ 1, true ]

**Comment by metahnetoutage** [comment]
git clone https://github.com/mzabriskie/react-example.git
cd react-example
npm run setup
npm run dev
open http://localhost:8080
