### ISSUE TITLE
GitHub API tests not working

### ISSUE THREAD

**Issue by kentcdodds** [mzabriskie/react-example#6]
Check out [the tests](https://github.com/mzabriskie/react-example/blob/ffee997ce87448de8caa81702959b49c790131ef/app/screens/User/util/github-api.test.js) for the GitHub API module and you'll see that they're skipped. That's because I couldn't figure out how to get things working. From all I can tell, I'm using the API right, but the tests are failing for some reason. Could you help out @mzabriskie?

**Comment by mzabriskie** [comment]
I was able to fix part of the problem, but now am getting an error from sinon:

``` js
1) GitHub API getUserData should make a request to the proper urls for the given user:
     Uncaught TypeError: Cannot read property 'replace' of undefined
      at Object.callProto.toString (node_modules/sinon/lib/sinon/call.js:183:56)
      at spyApi.formatters.C (node_modules/sinon/lib/sinon/spy.js:397:75)
      at node_modules/sinon/lib/sinon/spy.js:301:42
      at RegExp.[Symbol.replace] (native)
      at String.replace (native)
      at Function.spyApi.printf (node_modules/sinon/lib/sinon/spy.js:297:39)
      at printfArray (node_modules/sinon-chai/lib/sinon-chai.js:55:31)
      at affirmative (node_modules/sinon-chai/lib/sinon-chai.js:60:24)
      at Object.module.exports [as getMessage] (node_modules/chai/lib/chai/utils/getMessage.js:43:39)
      at Assertion.assert (node_modules/chai/lib/chai/assertion.js:105:22)
      at Assertion.<anonymous> (node_modules/sinon-chai/lib/sinon-chai.js:95:18)
      at Assertion.ctx.(anonymous function) [as calledWith] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Timeout._onTimeout (github-api.test.js:54:45)
```

**Comment by kentcdodds** [comment]
Hmmm... Wanna make a PR with what you have so far?

**Comment by kentcdodds** [comment]
Or heck, just commit it...

**Comment by kentcdodds** [comment]
Oh, noticed you already did 😅 https://github.com/mzabriskie/react-example/commit/8f822259c4599194c3fc47f580ed0c192aa77881

**Comment by kentcdodds** [comment]
Fixed! https://github.com/mzabriskie/react-example/commit/acad656679bc028de6a859908512085d67a2a4d6

Team work!

![high-five-hi-hi-5-l41lHvfYqxWus1oYw](https://camo.githubusercontent.com/d62469d9f352c33dc2a55dd8eafe92157d993de5/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6c34316c487666597178577573316f59772f67697068792e676966)
